import Head from "next/head";
import React from "react";
import Navbar from "../navbar/navbar";
import Footer from "../footer/footer";
interface Props {
  children?: JSX.Element;
}

export default function Layout({ children }: Props) {
  return (
    <div className="flex min-h-screen w-screen select-none flex-col items-center justify-start bg-background-primary text-foreground-primary">
      <Head>
        <title>Buddy</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, user-scalable=no" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-1 w-full justify-center px-6 pt-14 pb-12">
        {children}
      </div>
      <Navbar />
    </div>
  );
}
